source 'https://rubygems.org'

gem 'rails', '4.2.2'

gem 'rails-api'

gem 'spring', :group => :development

gem 'sqlite3'

gem 'versionist'

gem 'active_model_serializers'

group :development do
  gem 'byebug'
end
